### ISSUE TITLE
Exception thrown when decrypting Packet with incorrect Recipient key

### ISSUE THREAD

**Issue by OnTheFenceDevelopment** [OnTheFenceDevelopment/PersonalEncryptorCLI#3]
Attempts to decrypt a Packet using an Incorrect recipient, i.e. Private, key result in a cryptographic exception:

Unhandled Exception: System.Security.Cryptography.CryptographicException: The parameter is incorrect.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.RSACryptoServiceProvider.DecryptKey(SafeKeyHandle pKeyContext, Byte[] pbEncryptedKey, Int32 cbEncryptedKey, Boolean fOAEP, ObjectHandleOnStack ohRetDecryptedKey)
   at System.Security.Cryptography.RSACryptoServiceProvider.Decrypt(Byte[] rgb, Boolean fOAEP)
   at OnTheFenceDevelopment.PersonalEncryptorCLI.RSAEncryption.DecryptData(Byte[] dataToEncrypt, Int32 keyLength, String pathToPrivateKey) in C:\Code\PersonalEncryptorCLI\PersonalEncryptorCLI\RSAEncryption.cs:line 50
   at OnTheFenceDevelopment.PersonalEncryptorCLI.HybridEncryption.DecryptData(EncryptedPacket encryptedPacket, Int32 keyLength, RSAEncryption rsaParams, DigitalSignature digitalSignature, String pathToRecipientPrivateKey, String pathToSenderPublicKey) in C:\Code\PersonalEncryptorCLI\PersonalEncryptorCLI\HybridEncryption.cs:line 31
   at OnTheFenceDevelopment.PersonalEncryptorCLI.Program.Decrypt(EncryptedPacket encryptedPacket, Int32 keyLength, String sendersPublicKeyPath, String recipientsPrivateKeyPath) in C:\Code\PersonalEncryptorCLI\PersonalEncryptorCLI\Program.cs:line 161
   at OnTheFenceDevelopment.PersonalEncryptorCLI.Program.DecryptFileOptions(DecryptFileOptions opts) in C:\Code\PersonalEncryptorCLI\PersonalEncryptorCLI\Program.cs:line 114
   at OnTheFenceDevelopment.PersonalEncryptorCLI.Program.<>c.<Main>b__0_2(DecryptFileOptions opts) in C:\Code\PersonalEncryptorCLI\PersonalEncryptorCLI\Program.cs:line 18
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 notParsedFunc)
   at OnTheFenceDevelopment.PersonalEncryptorCLI.Program.Main(String[] args) in C:\Code\PersonalEncryptorCLI\PersonalEncryptorCLI\Program.cs:line 1

**Comment by OnTheFenceDevelopment** [comment]
Added simple exception handling at the top level - could be improved with some custom exceptions but fine for MVP
